#!/usr/bin/env python

"""
Author: Nick Russo (njrusmc@gmail.com)
Purpose: Trivial NetFlow analyzer for gzip files generated by the
Python 'netflow' package's built-in collector. Prints individual
NetFlow entries as raw JSON dictionaries to stdout; nothing more.
Requires one CLI argument specifying the gzip file to analyze.
Start collector: python3 -m netflow.collector -p 2055 -D
"""

import gzip
import json
import sys

# Require exactly 2 CLI arguments
if len(sys.argv) != 2:
    print("usage: nf_json.py <file.gz>")
    sys.exit(1)

# Open collector-generated file for review
with gzip.open(sys.argv[1], "rb") as gzipped:

    # For each netflow entry, load JSON into string and print
    for line in gzipped:
        entry = json.loads(line)
        print(json.dumps(entry, indent=2))