{
 "title": "performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CDP neighbor updates",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "CDP neighbor hostnames",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XE-cdp-oper:cdp-neighbor-details/cdp-neighbor-detail",
     "select": [
      [
       { "params": [ "device_name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU 5sec",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
     "select": [
      [
       { "params": [ "five_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
     "select": [
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
     "select": [
      [
       { "params": [ "used_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
     "select": [
      [
       { "params": [ "free_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}