{
  "response": [
    {
      "type": "Cisco ASR 1001-X Router",
      "family": "Routers",
      "errorCode": "DEV-UNREACHED",
      "lastUpdated": "2019-07-23 18:18:58",
      "tagCount": "1",
      "location": null,
      "role": "DISTRIBUTION",
      "lastUpdateTime": 1563905938354,
      "macAddress": "00:c8:8b:80:bb:00",
      "serialNumber": "FXS1932Q1SE",
      "softwareVersion": "16.3.2",
      "hostname": "asr1001-x.mel.mel",
      "locationName": null,
      "upTime": "26 days, 23:06:06.79",
      "inventoryStatusDetail": "<status><general code=\"DEV_UNREACHED\"/></status>",
      "errorDescription": "SNMP timeouts are occurring with this device. Either the SNMP credentials are not correctly provided to controller or the device is responding slow and snmp timeout is low. If its a timeout issue, controller will attempt to progressively adjust the timeout in subsequent collection cycles to get device to managed state. User can also run discovery again only for this device using the discovery feature after adjusting the timeout and snmp credentials as required. Or user can update the timeout and snmp credentials as required using update credentials.",
      "softwareType": "IOS-XE",
      "collectionInterval": "Global Default",
      "roleSource": "MANUAL",
      "apManagerInterfaceIp": "",
      "associatedWlcIp": "",
      "bootDateTime": "2018-10-14 16:59:30",
      "collectionStatus": "Partial Collection Failure",
      "interfaceCount": "12",
      "lineCardCount": "9",
      "lineCardId": "19557762-4170-42c0-b4ae-c539ee996a05, 184ddd93-2fc2-4baa-aa66-67e4e2948399, c5987ca2-3f69-4341-8cf5-00431f3add0c, ab808a88-85a0-434f-895d-7b98cd0e25fb, 1e38a03d-c5dd-46dc-8038-74e83b3da5ca, ba411ee4-6e98-4bf4-afdd-1601fcc5b9e9, 454acd43-5b66-4912-a692-bb00a9725267, d5e53e21-6e3d-4e8f-881a-ea619b133511, f4fc3497-9624-44d1-b32e-4b074706727c",
      "managementIpAddress": "10.10.22.253",
      "memorySize": "3819298032",
      "platformId": "ASR1001-X",
      "reachabilityFailureReason": "SNMP Connectivity Failed",
      "reachabilityStatus": "Unreachable",
      "series": "Cisco ASR 1000 Series Aggregation Services Routers",
      "snmpContact": "",
      "snmpLocation": "",
      "tunnelUdpPort": null,
      "waasDeviceMode": null,
      "instanceUuid": "1904ca0d-01be-4d13-88e5-4f4f9980b512",
      "instanceTenantId": "5bd3634ab2bea0004c3ebb58",
      "id": "1904ca0d-01be-4d13-88e5-4f4f9980b512"
    },
    {
      "type": null,
      "family": null,
      "errorCode": null,
      "lastUpdated": "2019-07-23 18:15:48",
      "tagCount": "0",
      "location": null,
      "role": "UNKNOWN",
      "lastUpdateTime": 1563905748302,
      "macAddress": null,
      "serialNumber": null,
      "softwareVersion": null,
      "hostname": null,
      "locationName": null,
      "upTime": null,
      "inventoryStatusDetail": "<status><general code=\"SYNC\"/></status>",
      "errorDescription": null,
      "softwareType": null,
      "collectionInterval": "Global Default",
      "roleSource": "AUTO",
      "apManagerInterfaceIp": "",
      "associatedWlcIp": "",
      "bootDateTime": null,
      "collectionStatus": "In Progress",
      "interfaceCount": null,
      "lineCardCount": null,
      "lineCardId": null,
      "managementIpAddress": "192.0.2.2",
      "memorySize": "NA",
      "platformId": null,
      "reachabilityFailureReason": "",
      "reachabilityStatus": "Unreachable",
      "series": null,
      "snmpContact": null,
      "snmpLocation": null,
      "tunnelUdpPort": null,
      "waasDeviceMode": null,
      "instanceUuid": "181a0fcb-e56e-4833-a92a-ec9932be427c",
      "instanceTenantId": "5bd3634ab2bea0004c3ebb58",
      "id": "181a0fcb-e56e-4833-a92a-ec9932be427c"
    },
    {
      "type": null,
      "family": null,
      "errorCode": "DEV-UNREACHED",
      "lastUpdated": "2019-07-23 18:41:50",
      "tagCount": "0",
      "location": null,
      "role": "UNKNOWN",
      "lastUpdateTime": 1563907310048,
      "macAddress": null,
      "serialNumber": null,
      "softwareVersion": null,
      "hostname": null,
      "locationName": null,
      "upTime": null,
      "inventoryStatusDetail": "<status><general code=\"DEV_UNREACHED\"/></status>",
      "errorDescription": "SNMP timeouts are occurring with this device. Either the SNMP credentials are not correctly provided to controller or the device is responding slow and snmp timeout is low. If its a timeout issue, controller will attempt to progressively adjust the timeout in subsequent collection cycles to get device to managed state. User can also run discovery again only for this device using the discovery feature after adjusting the timeout and snmp credentials as required. Or user can update the timeout and snmp credentials as required using update credentials.",
      "softwareType": null,
      "collectionInterval": "Global Default",
      "roleSource": "AUTO",
      "apManagerInterfaceIp": "",
      "associatedWlcIp": "",
      "bootDateTime": null,
      "collectionStatus": "Could Not Synchronize",
      "interfaceCount": null,
      "lineCardCount": null,
      "lineCardId": null,
      "managementIpAddress": "192.0.2.1",
      "memorySize": "NA",
      "platformId": null,
      "reachabilityFailureReason": "SNMP Connectivity Failed",
      "reachabilityStatus": "Unreachable",
      "series": null,
      "snmpContact": null,
      "snmpLocation": null,
      "tunnelUdpPort": null,
      "waasDeviceMode": null,
      "instanceUuid": "3ab79a68-4a3a-4cdc-b41e-eb98dabcdb84",
      "instanceTenantId": "5bd3634ab2bea0004c3ebb58",
      "id": "3ab79a68-4a3a-4cdc-b41e-eb98dabcdb84"
    },
    {
      "type": null,
      "family": null,
      "errorCode": "DEV-UNREACHED",
      "lastUpdated": "2019-07-23 18:23:35",
      "tagCount": "0",
      "location": null,
      "role": "UNKNOWN",
      "lastUpdateTime": 1563906215241,
      "macAddress": null,
      "serialNumber": null,
      "softwareVersion": null,
      "hostname": null,
      "locationName": null,
      "upTime": null,
      "inventoryStatusDetail": "<status><general code=\"DEV_UNREACHED\"/></status>",
      "errorDescription": "SNMP timeouts are occurring with this device. Either the SNMP credentials are not correctly provided to controller or the device is responding slow and snmp timeout is low. If its a timeout issue, controller will attempt to progressively adjust the timeout in subsequent collection cycles to get device to managed state. User can also run discovery again only for this device using the discovery feature after adjusting the timeout and snmp credentials as required. Or user can update the timeout and snmp credentials as required using update credentials.",
      "softwareType": null,
      "collectionInterval": "Global Default",
      "roleSource": "AUTO",
      "apManagerInterfaceIp": "",
      "associatedWlcIp": "",
      "bootDateTime": null,
      "collectionStatus": "Could Not Synchronize",
      "interfaceCount": null,
      "lineCardCount": null,
      "lineCardId": null,
      "managementIpAddress": "192.0.2.3",
      "memorySize": "NA",
      "platformId": null,
      "reachabilityFailureReason": "SNMP Connectivity Failed",
      "reachabilityStatus": "Unreachable",
      "series": null,
      "snmpContact": null,
      "snmpLocation": null,
      "tunnelUdpPort": null,
      "waasDeviceMode": null,
      "instanceUuid": "7efadae4-0023-434f-8ae6-0bbc3c51ff2c",
      "instanceTenantId": "5bd3634ab2bea0004c3ebb58",
      "id": "7efadae4-0023-434f-8ae6-0bbc3c51ff2c"
    },
    {
      "type": null,
      "family": null,
      "errorCode": "DEV-UNREACHED",
      "lastUpdated": "2019-07-23 18:25:57",
      "tagCount": "0",
      "location": null,
      "role": "UNKNOWN",
      "lastUpdateTime": 1563906357351,
      "macAddress": null,
      "serialNumber": null,
      "softwareVersion": null,
      "hostname": null,
      "locationName": null,
      "upTime": null,
      "inventoryStatusDetail": "<status><general code=\"DEV_UNREACHED\"/></status>",
      "errorDescription": "SNMP timeouts are occurring with this device. Either the SNMP credentials are not correctly provided to controller or the device is responding slow and snmp timeout is low. If its a timeout issue, controller will attempt to progressively adjust the timeout in subsequent collection cycles to get device to managed state. User can also run discovery again only for this device using the discovery feature after adjusting the timeout and snmp credentials as required. Or user can update the timeout and snmp credentials as required using update credentials.",
      "softwareType": null,
      "collectionInterval": "Global Default",
      "roleSource": "AUTO",
      "apManagerInterfaceIp": "",
      "associatedWlcIp": "",
      "bootDateTime": null,
      "collectionStatus": "Could Not Synchronize",
      "interfaceCount": null,
      "lineCardCount": null,
      "lineCardId": null,
      "managementIpAddress": "192.0.2.4",
      "memorySize": "NA",
      "platformId": null,
      "reachabilityFailureReason": "SNMP Connectivity Failed",
      "reachabilityStatus": "Unreachable",
      "series": null,
      "snmpContact": null,
      "snmpLocation": null,
      "tunnelUdpPort": null,
      "waasDeviceMode": null,
      "instanceUuid": "ea400390-f224-4587-a11e-a941c68bd141",
      "instanceTenantId": "5bd3634ab2bea0004c3ebb58",
      "id": "ea400390-f224-4587-a11e-a941c68bd141"
    }
  ],
  "version": "1.0"
}
