---
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "db"
  labels:
    role: "db"
spec:
  containers:
    - name: "db"
      image: "mysql:latest"
      args:
        - "--default-authentication-plugin=mysql_native_password"
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "globomantics"
        - name: "MYSQL_DATABASE"
          value: "db"
...
